# Generated by Django 4.1.1 on 2022-09-17 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PhoneNum', models.CharField(max_length=255)),
                ('Timeline', models.CharField(max_length=255)),
            ],
        ),
    ]
